const MimeTypes = {
  imageTypes: [
    "image/apng",
    "image/bmp",
    "image/gif",
    "image/x-icon",
    "image/jpeg", 
    "image/png",
    "image/webp",
    "image/svg+xml",
  ],
  audioTypes: [
    "audio/webm",
    "audio/wave",
    "audio/wav",
    "audio/ogg",
    "audio/opus",
    "audio/mpeg",
    "audio/flac",
    "audio/aac",
    "audio/x-wav",
    "audio/wave",
    "audio/x-flac",
    "audio/x-ogg",
    "audio/x-mpeg"
  ],
  videoTypes: [
    "video/x-msvideo",
    "video/mpeg", 
    "video/ogg",
    "video/mp4",
    "video/webm",
    "video/3gpp",
    "video/quicktime"
  ],
  specialTypes: [
    "application/pdf"
  ],
  textTypes: [
    "text/plain",
    "text/markdown"
  ],
  codeTypes: [
    "text/html",
    "text/css",
    "text/javascript",
    "application/javascript",
    "application/json",
    "application/xml",
    "text/x-actionscript",
    "text/x-ada",
    "text/x-applescript",
    "text/x-asm",
    "text/x-asp",
    "text/x-awk",
    "text/x-assembly",
    "text/x-autohotkey",
    "text/x-bash",
    "text/x-basic",
    "text/x-c",
    "text/x-c++src",
    "text/x-csharp",
    "text/x-cobol",
    "text/x-csp",
    "text/x-css",
    "text/x-d",
    "text/x-dart",
    "text/x-diff",
    "text/x-eiffel",
    "text/x-elisp",
    "text/x-erlang",
    "text/x-fortran",
    "text/x-fsharp",
    "text/x-go",
    "text/x-groovy",
    "text/x-haskell",
    "text/x-idl",
    "text/x-java",
    "text/x-java-source",
    "text/x-javascript",
    "text/x-lisp",
    "text/x-lua",
    "text/x-makefile",
    "text/x-matlab",
    "text/x-mips-assembler",
    "text/x-nasm",
    "text/x-nsis",
    "text/x-objectivec",
    "text/x-prolog",
    "text/x-pascal",
    "text/x-perl",
    "text/x-php",
    "text/x-pig",
    "text/x-pike",
    "text/x-python",
    "text/x-qml",
    "text/x-r",
    "text/x-rebol",
    "text/x-ruby",
    "text/x-rustsrc",
    "text/x-scala",
    "text/x-scheme",
    "text/x-scss",
    "text/x-sh",
    "text/x-sql",
    "text/x-tcl",
    "text/x-tex",
    "text/x-vb",
    "text/x-vbscript",
    "text/x-verilog",
    "text/x-vhdl",
    "text/x-yaml",
    "text/x-z80"
  ],
  archiveTypes: [
    "application/x-xz",
    "application/zip",
    "application/x-zip-compressed",
    "application/gzip",
    "application/gzip-compressed",
    "application/x-gzip",
    "application/x-compressed",
    "application/x-rar",
    "application/x-rar-compressed",
    "application/x-tar",
    "application/x-bzip",
    "application/x-bzip2",
    "application/x-7z-compressed",
    "application/x-lzma",
    "application/x-gtar",
    "application/x-xz",
  ],
  executableTypes: [
    "application/x-executable",
    "application/x-dosexec",
    "application/x-elf",
    "application/x-ms-dos-executable",
    "application/x-sharedlib"
  ],
  diskTypes: [
    "application/x-iso9660-image",
    "application/x-cd-image",
    "application/x-vhd",
    "application/x-vmdk",
    "application/x-apple-diskimage",
    "application/x-ms-dos-diskimage"
  ],
  previewTypes: [""]
};

// Collect preview types
MimeTypes.previewTypes = MimeTypes.imageTypes.concat(MimeTypes.audioTypes.concat(MimeTypes.videoTypes.concat(MimeTypes.specialTypes.concat(MimeTypes.textTypes.concat(MimeTypes.codeTypes)))));
// we don't actually use textTypes outside of previewing, so combine them with codeTypes
MimeTypes.textTypes = MimeTypes.textTypes.concat(MimeTypes.codeTypes);

export default MimeTypes;
